project_id = "quskamnfwglctqewwfln"

[functions.shared-mugshot]
verify_jwt = false

[functions.shared-profile]
verify_jwt = false

[functions.public-cafe-list]
verify_jwt = false

[functions.deliver-activity]
verify_jwt = false
