//
//  Guide.swift
//  testMugshot
//
//  Model for curated cafe collections (Mugshot Guides).
//  Designed to be LLM-ready for future auto-generation via Supabase Edge Functions.
//

import Foundation

struct Guide: Identifiable, Codable {
    let id: UUID
    let title: String
    let subtitle: String
    let coverEmoji: String
    let colorHex: String
    let cafeIds: [UUID]
    
    init(
        id: UUID = UUID(),
        title: String,
        subtitle: String,
        coverEmoji: String,
        colorHex: String,
        cafeIds: [UUID] = []
    ) {
        self.id = id
        self.title = title
        self.subtitle = subtitle
        self.coverEmoji = coverEmoji
        self.colorHex = colorHex
        self.cafeIds = cafeIds
    }
    
    /// Mock guides for MVP. In production, these will be generated by an LLM
    /// and stored in Supabase `public.guides` table.
    static func mockGuides() -> [Guide] {
        return [
            Guide(
                title: "Hidden Gems",
                subtitle: "Top rated spots the crowds haven't found yet",
                coverEmoji: "💎",
                colorHex: "6B4E3D"
            ),
            Guide(
                title: "Matcha Paradise",
                subtitle: "Best green tea lattes in the city",
                coverEmoji: "🍵",
                colorHex: "7CB889"
            ),
            Guide(
                title: "Work & Focus",
                subtitle: "Quiet vibes, strong wifi, good outlets",
                coverEmoji: "💻",
                colorHex: "4A90E2"
            ),
            Guide(
                title: "Date Night",
                subtitle: "Cozy spots with great ambiance",
                coverEmoji: "✨",
                colorHex: "E91E63"
            )
        ]
    }
}

